import { readdir } from "node:fs/promises";
import path from "node:path";
import type { GeneratedFile } from "./types.ts";

const CLIENT_MODULE = /\.client\.tsx?$/;
export const GENERATED_CONTROLLERS_MARKER = "// Generated by @mewhhaha/ruwuter/vite — do not edit.";
const reservedWords = new Set([
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "debugger",
  "default",
  "delete",
  "do",
  "else",
  "export",
  "extends",
  "finally",
  "for",
  "function",
  "if",
  "import",
  "in",
  "instanceof",
  "let",
  "new",
  "return",
  "super",
  "switch",
  "this",
  "throw",
  "try",
  "typeof",
  "var",
  "void",
  "while",
  "with",
  "yield",
  "await",
  "enum",
  "implements",
  "interface",
  "package",
  "private",
  "protected",
  "public",
  "static",
  "null",
  "true",
  "false",
  "arguments",
  "eval",
]);

const controllerName = (file: string): string => {
  const base = path.basename(file).replace(CLIENT_MODULE, "");
  const parts = base.split(/[^A-Za-z0-9_$]+/).filter(Boolean);
  const name = parts.map((part, index) => {
    if (index === 0) return part.slice(0, 1).toLowerCase() + part.slice(1);
    return part.slice(0, 1).toUpperCase() + part.slice(1);
  }).join("") || "controller";
  return /^[A-Za-z_$]/.test(name) && !reservedWords.has(name) ? name : `controller${name}`;
};

const findClientModules = async (folder: string): Promise<string[]> => {
  const entries = await readdir(folder, { withFileTypes: true });
  const files = await Promise.all(entries.map((entry) => {
    const entryPath = path.join(folder, entry.name);
    if (entry.isDirectory()) return findClientModules(entryPath);
    return entry.isFile() && CLIENT_MODULE.test(entry.name) ? [entryPath] : [];
  }));
  return files.flat();
};

/** Generates Vite-only `app/controllers.ts` typed controller-module references. */
export const generateControllers = async (appFolder: string): Promise<GeneratedFile[]> => {
  const resolvedAppFolder = path.resolve(appFolder);
  let modules: string[];
  try {
    modules = await findClientModules(resolvedAppFolder);
  } catch (error) {
    if ((error as { code?: string }).code === "ENOENT") return [];
    throw error;
  }
  modules.sort((left, right) => left < right ? -1 : left > right ? 1 : 0);

  const names = new Map<string, string>();
  const entries = modules.map((file) => {
    const name = controllerName(file);
    const previous = names.get(name);
    if (previous) {
      throw new Error(
        `Generated controller symbol collision between ${
          JSON.stringify(
            path.relative(resolvedAppFolder, previous),
          )
        } and ${JSON.stringify(path.relative(resolvedAppFolder, file))}: ${name}.`,
      );
    }
    names.set(name, file);
    const relative = path.relative(resolvedAppFolder, file).split(path.sep).join("/");
    const specifier = `./${relative}`;
    return `import ${name}Href from ${JSON.stringify(`${specifier}?ruwuter-controller-url`)};\n` +
      `type __${name}ControllerCheck = __RuwuterAssert<` +
      `import("@mewhhaha/ruwuter/browser").IsControllerModule<` +
      `typeof import(${JSON.stringify(specifier)})>>;\n` +
      `export const ${name} = ${name}Href as unknown as ` +
      `import("@mewhhaha/ruwuter/browser").ControllerHrefOf<` +
      `typeof import(${JSON.stringify(specifier)})>;`;
  });

  if (!entries.length) return [];
  const contents = [
    GENERATED_CONTROLLERS_MARKER,
    "// This file uses Vite controller-module URLs and is intentionally not generated by Deno-only tooling.",
    "type __RuwuterAssert<Value extends true> = Value;",
    ...entries,
    "",
  ].join("\n");
  return [{ path: path.join(resolvedAppFolder, "controllers.ts"), contents }];
};
